### ISSUE TITLE
NTR: diphthamide deficiency syndrome

### ISSUE THREAD

**Issue by srengel** [DiseaseOntology/HumanDiseaseOntology#1239] opened 2023-09-12 21:55 UTC
Include: 
- new disease terms or updates to DO's disease terms

NTR: diphthamide deficiency syndrome

- include the term name in the title of the request
- It is helpful to include a definition and PubMed reference for new terms

Autosomal recessive diphthamide deficiency syndrome presents as intellectual disability with developmental abnormalities, seizures, craniofacial and additional morphological phenotypes. It is caused by reduced activity of proteins that synthesize diphthamide on human translation elongation factor 2. Diphthamide synthesis requires seven proteins (DPH1-DPH7) with clinical deficiency described for DPH1, DPH2 and DPH5.

https://pubmed.ncbi.nlm.nih.gov/37675463/

- It is useful to share information on the relevant project 

trying to annotate the yeast orthologs at SGD https://www.yeastgenome.org/reference/S000345302

- include contact information along with your ORCID id, so that we can provide attribution for your contribution

Stacia Engel, SGD
www.yeastgenome.org
[0000-0001-5472-917X](http://orcid.org/0000-0001-5472-917X)

**Comment by allenbaron** [comment] 2023-10-05 23:01
Stacia, thanks for requesting this. Three diphthamide deficiency syndrome diseases will be in the next release (linked to mutations in the DPH1, DPH2 & DPH5 genes).

_Thanks for the great work you're doing at SGD. My apologies for the delayed response._

**Comment by allenbaron** [comment] 2023-10-10 19:28
Because dipthamide is an amino acid and this disease is caused by disruption of a metabolic process (post-translation modification of histidine to dipthamide), 'dipthamide deficiency syndrome' will be classified as an 'amino acid metabolic disorder' (DOID:9252).

**dipthamide structure** (from [Wikipedia](https://en.wikipedia.org/wiki/Diphthamide))
<img width="400" alt="Screenshot 2023-10-10 at 3 05 44 PM" src="https://github.com/DiseaseOntology/HumanDiseaseOntology/assets/21225409/29120916-f6b2-4ccb-a880-cea933af725c">

**Closed** 2023-10-11 16:58 UTC
