### ISSUE TITLE
DO release, files, definition label replaced by IAO_0000115

### ISSUE THREAD

**Issue by lschriml** [DiseaseOntology/HumanDiseaseOntology#997] opened 2021-11-16 19:38 UTC
Hello Becky,
   just noticed that for the HumanDO.owl and doid-non-classified.owl files, that the 
definition label has been replace by the IAO ID. 
   Not seeing this in the other files. 

Cheers,
Lynn

**Comment by allenbaron** [comment] 2022-07-19 23:15
I'm not sure I understand the problem correctly but it seems like this issue indicates that `IAO_0000115` in the HumanDO.owl and doid-non-classified.owl files had annotations on it, including `rdfs:label`, which it usually does not.

This may have been a specific issue with v2021-11-16. In that release, `IAO_0000115` in doid-non-classified.owl had annotations including a definition and `rdfs:label`...
<img width="1178" alt="Screen Shot 2022-07-19 at 6 40 39 PM" src="https://user-images.githubusercontent.com/21225409/179861211-ea4580fc-57cc-4f66-993a-89b21bc8267f.png">

... while `IAO_0000115` was a declared class _only_ in  doid-edit.owl and doid.owl without an `rdfs:label` (img from doid.owl). 
<img width="609" alt="Screen Shot 2022-07-19 at 6 40 15 PM" src="https://user-images.githubusercontent.com/21225409/179861210-b8660e8e-34e7-40d5-905e-298282e23bd1.png">

In the latest release ([v2022-06-07](https://github.com/DiseaseOntology/HumanDiseaseOntology/releases/tag/v2022-06-07)), `IAO_0000115` is not annotated in any of the products, except doid-merged.owl (it's always annotated there).

This does not appear to be an issue any longer.

**Comment by allenbaron** [comment] 2022-07-19 23:16
@lschriml do you have any other insights? Can this issue be closed?

**Comment by allenbaron** [comment] 2022-07-26 17:42
The issue is the missing label for `IAO_0000115` in those files. The label will be added to the doid-edit.owl file so that it propagates to these production files as well.

**Closed by allenbaron** 2022-07-26 17:42 UTC
