### ISSUE TITLE
review Opitz GBBB syndrome type II (DOID:0080698)

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#1028] opened 2022-04-11 16:16 UTC
recently OMIM discontinued OMIM:145410 (Opitz GBBB syndrome type II) and moved it into OMIM:145420 (Teebi hypertelorism syndrome 1) because of new evidence that, according to OMIM, "Teebi hypertelorism syndrome-1 (TBHS1) and Opitz GBBB syndrome type II (GBBB2), these disorders are considered to be the same"

**Comment by sbello** [comment] 2022-04-18 20:34
Hi @lschriml 
This turned up on the obsolete OMIM IDs in DO today. Looking at this OMIM merged 145410 into 145420. Only 145410 is an xref in DO.

Orphanet has entries for both Teebi hypertelorism syndrome that has the name "SPECC1L-related hypertelorism syndrome" (ORPHA:1519) and Opitz-GBBB syndrome (ORPHA:2745)

Orphanet defines Opitz-GBBB as an X-linked disease but had cross references to both OMIM 300000 and 145410 and 145410 is/was not X-linked.

The OMIM PS:300000 no longer exists (xref to DOID:0050780).

It seems like we should change [DOID:0080698](http://www.disease-ontology.org/?id=DOID:0080698) to Teebi hypertelorism syndrome type 1. Looking at the text changes in OMIM it appears that 145420 and 145410 were determined to be the same disease and DO does not have an entry that is equivalent to 145420. The definition for  DOID:0080698 really only specifies the gene and inheritance mode. We would need to change the parent for this term and fill in the phenotypic defining features as these have been revised.

This would leave only one subtype of Opitz-GBBB syndrome. Both OMIM and Orphanet have only Opitz-GBBB syndrome, OMIM converted type 1 back into to just Opitz-GBBB syndrome. So DO should probably merge [DOID:0080697](http://www.disease-ontology.org/?id=DOID:0080697) and DOID:0050780 into a single entry.

There is a second type of Teebi hypertelorism syndrome and a phenotypic series for this in OMIM but this does not appear to have entries in Orphanet.

**Comment by lschriml** [comment] 2022-05-11 16:28
Looking to see the nomenclature updates in PubMed references, and the status of the disease in OMIM, Orphaned, Medline Plus, as there have been additional updates since this ticket was initiated, here are my notes and the updates I'm making in the DO.  Thank you @sbello for working through these changes. 
I will update this ticket when the changes made today.

 **Opitz-GBBB syndrome (DOID:0050780)**
             --> merge DOID:0050780 into DOID:0080697
            --> remove OMIM: PS300000


===================================================
   **Opitz GBBB syndrome type I.  (DOID:0080697)**
      **--> DO updates:** 
                 --> disease name updated to: Opitz GBBB syndrome

                   --> update OMIM ID to: OMIM: 300000
                   --> definition: 
Opitz GBBB syndrome (GBBB) is a congenital midline malformation syndrome characterized by hypertelorism, hypospadias, cleft lip/palate, laryngotracheoesophageal abnormalities, imperforate anus, developmental delay, and cardiac defects, caused by mutation in the MID1 gene on chromosome Xp22.

                 --> reference: https://www.ncbi.nlm.nih.gov/books/NBK1327/           


                           Notes: 
                                - MID1 gene, on Xp22
                                - OMIM:300000
                                - X-linked recessive 
                               - OMIM update, renamed to : Opitz GBBB syndrome
                                 mutation in the MID1 gene on chromosome Xp22.2

         --> Opitz GBBB syndrome was first reported as 2 separate entities, BBB syndrome and G syndrome; subsequent reports of families in which the BBB and G syndromes segregated within a single kindred suggested that they represent a single entity.

                  Note: 
                   - Medline Plus: name has not been updated, term name: Opitz G/BBB syndrome
                             - https://medlineplus.gov/genetics/condition/opitz-g-bbb-syndrome/#synonyms

======================================================================
**[New DO term]:** 
          OMIM: 
                  **Teebi hypertelorism syndrome**. OMIM: PS145420

           GARD: 957, Brachycephalofrontonasal dysplasia
                                Other Names: 
                                 Craniofrontonasal dysplasia, Teebi type, Hypertelorism, Teebi type, Teebi hypertelorism syndrome
           (ORPHA:2745)


====================================================
        

Opitz GBBB syndrome type II.  (DOID:0080698) 
      --> DO updates: 
                 --> disease name change to: Teebi hypertelorism syndrome-1
                        OMIM ID update to: OMIM:145420

            add xrefs: - Orphanet: SPECC1L-related hypertelorism syndrome
                                  - ORPHA:1519
   
            add references: 
                   https://pubmed.ncbi.nlm.nih.gov/31953237/
                     https://pubmed.ncbi.nlm.nih.gov/30472488/


          OMIM changes: 
           - **OMIM:145410**.  --> moved to OMIM:145420
           - SPECC1L gene on chromosome 22q11.2 or heterozygous deletion at chromosome 22q11.2
                   - **New OMIM name**: **Teebi hypertelorism syndrome-1** 
                               - heterozygous mutation in the SPECC1L gene on chromosome 22q11.23
                               ---> The autosomal disorder is referred to in OMIM as TBHS1. 

           - Orphanet: SPECC1L-related hypertelorism syndrome
           - ORPHA:1519

https://pubmed.ncbi.nlm.nih.gov/31953237/
https://pubmed.ncbi.nlm.nih.gov/30472488/

         -->  we suggest that patients with pathogenic variants in SPECC1L should not be described as "dominant (or type 2) Opitz GBBB syndrome", and instead should be referred to as "SPECC1L syndrome" as both disorders show distinctive, non overlapping developmental anomalies beyond facial communalities.
         --> individuals with SPECCL1 variants have branchial fistulae, omphalocele, diaphragmatic hernias, and uterus didelphis
           -->  clinical overlap of SPECC1L syndrome with mild Baraitser-Winter craniofrontofacial syndrome: they share similar dysmorphic features (wide, short nose with a large tip, cleft lip and palate, blepharoptosis, retrognathia, and craniosynostosis), although intellectual disability, neuronal migration defect, and muscular problems remain largely specific to Baraitser-Winter syndrome

==========================================
   **New record:**  
                      OMIM: 619736. Teebi hypertelorism syndrome-2 
                     heterozygous mutation in the CDH11 gene on chromosome 16q21.

**Comment by lschriml** [comment] 2022-05-11 21:11
terms added, to do: add refs

**Comment by allenbaron** [comment] 2022-05-13 22:32
OMIM:145420 was included as a second definition source for the parent Teebi hypertelorism syndrome (DOID:0081073) because it describes the disease heterogeneity and history.

**Closed by allenbaron** 2022-05-13 22:32 UTC
