### ISSUE TITLE
term requests and 1 typo

### ISSUE THREAD

**Issue by slaulederkind** [DiseaseOntology/HumanDiseaseOntology#396] opened 2017-10-19 17:06 UTC
The following file has some requested term merges in it:

[DO merge requests 2017.xlsx](https://github.com/DiseaseOntology/HumanDiseaseOntology/files/1399341/DO.merge.requests.2017.xlsx)

One more thing.  The following term has "type 20", but it should be "type 2O":
Charcot-Marie-Tooth disease axonal type 20 (DOID:0110175)

Thanks.

**Comment by lschriml** [comment] 2017-10-19 17:23
Thank you Stan !!
I will take a look.

Cheers,
Lynn

**Comment by lschriml** [comment] 2017-11-15 20:48
Hello Stan,
 the typo is fixed. 
For the merges: 
(1) DOID:12594 (Potter's syndrome) and DOID:14766 (renal agenesis), looking at the evidence, I have made DOID:12594 a child of DOID:14766 (see:https://omim.org/entry/191830).

(2)  DOID:12028 (Conn's syndrome) with DOID:446 (hyperaldosteronism). 
         -- I have merged the two diseases, and updated the name to: primary hyperaldosteronism 

--> I am still looking at the other merges, will finish these shortly. 
Cheers,
Lynn

**Comment by lschriml** [comment] 2018-02-07 20:23
lipid-rich carcinoma and lipid-rich breast carcinoma. 
        lipid-rich breast carcinoma is a type of lipid-rich carcinoma. 
  --> I have updated the parentage of this term and added definitions. 

Powassan encephalitis --> moved to be a child of tick-borne encephalitis

alcohol abuse (habitual misuse of alcohol) and alcohol dependence (- alcoholism - ) are two distinct conditions.
DSM V has merged them into alcohol use disorder 
    -- for now at least I am keeping them two distinct diseases

eosinophilic pneumonia:
A pneumonia in which certain type of white blood cell called an eosinophil accumulates in the lung. These cells cause disruption of the normal air spaces (alveoli) where oxygen is extracted from the atmosphere. It is caused by certain medications or environmental triggers, parasitic infections, and cancer. The most common symptoms include cough, fever, difficulty breathing, and sweating at night.

and 
 pulmonary eosinophilia is --> an accumulation of eosinophils in the lungs

--> these are two distinct diseases.

**Closed by lschriml** 2018-02-07 20:23 UTC
Labels: enhancement
