### ISSUE TITLE
Couple of new terms for missing OMIM diseases for the gene CACNA1C

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1287] opened 2024-01-18 22:21 UTC
In OMIM CACNA1C  is associated with 4 disease but only 2 of these are in DO. Please add new terms for: 

https://www.omim.org/entry/618447 
Long QT syndrome 8 
child of DOID:2843
definition:  A long QT syndrome that has_material_basis_in dominant inheritance of mutation in the CACNA1C gene on chromosome 12p13.33.
ref: PMID:10220144

Possibly this is the same as Timothy syndrome. OMIM has separate records for these but Orphanet and GARD combines these in a single record (https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=65283 and https://rarediseases.info.nih.gov/diseases/9294/disease) 

Note that the Long QT syndrome series is also missing other members, see https://www.omim.org/phenotypicSeries/PS192500?sort=phenotype for review

https://www.omim.org/entry/620029
Neurodevelopmental disorder with hypotonia, language delay, and skeletal defects with or without seizures
child of DOID:0060307
definition:  An autosomal dominant intellectual developmental disorder characterized by global developmental delay apparent from infancy, severe hypotonia, poor or absent speech, impaired intellectual development with behavioral abnormalities, and mild skeletal defects that has_material_basis_in heterozygous missense or truncating mutations in the CACNA1C gene on chromosome 12p13.
ref: PMID:34163037

**Comment by allenbaron** [comment] 2024-01-19 16:50
Will do. I will work to get them into the February release.

**Comment by allenbaron** [comment] 2024-02-26 18:12
Taking a look at this now.

## LQT8 & Timothy syndrome
It looks like LQT8 (DOID:0110649) and Timothy syndrome (DOID:0060173) were both in the DO previously and merged because they were given the same name (#267). LQT8/DOID:0110649 was added shortly before the merger (in 53e742431b056ab40421ead756ab81f48cb084b0 on Feb 13 2017), while Timothy syndrome/DOID:0060173 pre-dates the DO's move to git/GitHub.

- OMIM does indeed have one entry for each.
- Orphanet does not but based on the cross-references in the latest release of ORDO (4.4), they don't consider them exactly the same either. Orphanet's Timothy syndrome (ORDO:65283) has OMIM:601005 (TIMOTHY SYNDROME) as an exact match and OMIM:618447 (LONG QT SYNDROME 8) as a broader match (NTBT in their vernacular). Based on that, _it seems they consider Timothy syndrome a subtype of LQT8._
- A 2021 publication reviewing the molecular complexities of Timothy syndrome holds that LQT8 continue to be consider separate from Timothy syndrome, as a non-syndromic subtype (https://pubmed.ncbi.nlm.nih.gov/34079780).
- A 2023 publication (https://pubmed.ncbi.nlm.nih.gov/37132248/) initially describes Timothy syndrome as LQT8 but then states the following which seems to agree with Orphanet's opinion of LQT8, that it's a broader term than Timothy syndrome:
    > Although in some of these CACNA1C variants, TS-related extra-cardiac phenotype was not always found, only with QT prolongation and arrhythmia, thus described as non-TS LQT8 (Ref. [16](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10407238/#ref16)).
- Another 2023 publication (https://pubmed.ncbi.nlm.nih.gov/37614386/) states:
    > Interestingly, depending on the gain- or loss-of-function nature of the variation, this gene has been associated with other syndromes like nonsyndromic long QT syndrome 8, short QT, and Brugada syndrome.
- A third 2023 publication (https://pubmed.ncbi.nlm.nih.gov/36598608/) seems to consider Timothy syndrome and LQT8 as equivalent, stating:
    > Timothy syndrome (TS) was initially identified in the early 1990s as a severe form of long-QT syndrome, comorbid with syndactyly([63](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10576998/#R63), [64](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10576998/#R64), [65](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10576998/#R65)). This rare clinical disorder would eventually be the first documented CaV1.2 channelopathy, and has been designated as long QT type 8 (LQT8).

So it seems invocation of LQT8 in the literature has been used as a grouping term (as it is in Orphanet) _and_ as a non-syndromic variant of long QT.

**Comment by allenbaron** [comment] 2024-02-26 18:15
## NEDHLSS
The literature seems clear in defining 'Neurodevelopmental disorder with hypotonia, language delay, and skeletal defects with or without seizures' as separate from Timothy syndrome but I'm wondering how to handle the phenotypic variability.

OMIM has defined this disease based on the patients with missense mutations as described by https://pubmed.ncbi.nlm.nih.gov/34163037/, but there is another set of patients with truncating mutations with a fairly discernable phenotype that OMIM has included with the comment:

> Individuals with truncating variants in the CACNA1C gene have also been described

 I favor creating two diseases to distinguish the missense and truncating patient populations... primarily because it's easier to lump later than split. @sbello, @lschriml thoughts?

**Comment by allenbaron** [comment] 2024-02-26 18:19
## Tentative Plan

@sbello & @lschriml, this is a bit complicated so I welcome your thoughts on how best to proceed. So here's what I'm thinking:

- Unobsolete DOID:0110649 as a child of LQT syndrome (DOID:2843), using LQT8 as the name (it was only in the release of v2017-02-17, so it has likely not been used) and move any LQT8-specific xrefs from Timothy syndrome.
    - It makes more sense to me to split the non-syndromic version of a disease out as it's own disease and not to use it as a grouping term. 
    - Since OMIM is the authority that initially defined LQT8, I think it makes sense to stick with their definition, limiting it to non-syndromic LQT.
-  I suggest we leave Timothy syndrome as is for the time being (though we could probably create diseases for type 1 & type 2 if we wanted to).
- Add NEDHLSS as @sbello suggested and specify that it's caused by missense mutations as OMIM has. We can always come back and add another disease for the patients with truncations, as new publications are released.

**Comment by sbello** [comment] 2024-02-26 20:43
The primary upside to lumping missense and truncation into a single entry is that it makes it easier to attach models to disease where the phenotype may be the same but the mutation type may differ. It is really helpful to have a less specific term or parent term that is more specific than 'syndrome'.
Points 1 and 2 make sense to me.

**Comment by allenbaron** [comment] 2024-02-26 21:54
Just noting additional sources/references that treat 'Timothy syndrome' and LQT8 as equivalent:
- https://medlineplus.gov/genetics/condition/timothy-syndrome
- https://meshb.nlm.nih.gov/record/ui?ui=C536962
- https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C142894
- https://uts.nlm.nih.gov/uts/umls/concept/C1832916 (also SNOMED, which appears to be a copy of Orphanet... or the other way around)

These don't alter my plan but they will complicate mapping to these resources. The phenotypic separation & classification for Timothy syndrome appears to be a mess right now. OMIM is still most likely to be correct.

**Comment by allenbaron** [comment] 2024-02-26 21:58
I understand your comment about lumping the mutants for NEDHLSS. Since OMIM has included both mutation types, I will also include them both. We can always split them later if the distinction becomes more definitive.

**Closed** 2024-02-28 15:54 UTC
Labels: OMIM
